NOTION_API_KEY = ""
NOTION_PAGE_ID = ""
NOTION_DATABASE_ID = ""
VELOG_GOOGLE_ID = ""
VELOG_GOOGLE_PASSWORD = ""

# 대기 시간 설정 (초)
SEC_WAIT_VERY_SHORT = 5
SEC_WAIT_SHORT = 30
SEC_WAIT_MID = 60
SEC_WAIT_VERY_MID = 120
SEC_WAIT_LONG = 180
SEC_WAIT_VERY_LONG = 300