from _typeshed import Incomplete
from docassemble.base.generate_key import random_string as random_string

dbtableprefix: Incomplete
daconfig: Incomplete
s3_config: Incomplete
S3_ENABLED: bool
gc_config: Incomplete
GC_ENABLED: bool
azure_config: Incomplete
AZURE_ENABLED: bool
hostname: Incomplete
loaded: bool
in_celery: bool
in_cron: bool
errors: Incomplete
env_messages: Incomplete
allowed: Incomplete

def env_true_false(var): ...
def env_exists(var): ...
def env_translate(var): ...
def override_config(the_config, messages, key, var, pre_key: Incomplete | None = ...) -> None: ...
def config_error(error) -> None: ...
def cleanup_filename(filename): ...
def delete_environment() -> None: ...

this_thread: Incomplete

def aws_get_region(arn): ...
def aws_get_secret(data): ...
def azure_get_secret(data): ...
def recursive_fetch_cloud(data): ...
def fix_authorized_domain(domain): ...
def load(**kwargs) -> None: ...
def default_config(): ...
def parse_redis_uri(): ...
def noquote(string): ...
