type tsearchLangSpecificEnum = {
  [key: string]: string;
};
export const searchLangSpecificEnum: tsearchLangSpecificEnum = {
  bat: 'Batch',
  cc: 'C++ Source',
  hh: 'C++ H-Header',
  h: 'C++ Header',
  c: 'C',
  cs: 'C#',
  cpp: 'C++',
  css: 'CSS',
  clj: 'Clojure',
  coffee: 'Coffee',
  dart: 'Dart',
  erl: 'Erlang',
  ex: 'Elixir',
  el: 'Lisp',
  go: 'Go',
  groovy: 'Groovy',
  hs: 'Haskell',
  html: 'HTML',
  htm: 'HTM',
  java: 'Java',
  js: 'JavaScript',
  json: 'JSON',
  kt: 'Kotlin',
  lua: 'Lua',
  md: 'Markdown',
  matlab: 'MATLAB',
  m: 'Objective-C',
  pl: 'Perl',
  php: 'PHP',
  py: 'Python',
  pyc: 'Python-C',
  ps1: 'PowerShell',
  rb: 'Ruby',
  r: 'R',
  rs: 'Rust',
  scala: 'Scala',
  sh: 'Bash',
  sql: 'SQL',
  swift: 'Swift',
  tex: 'TeX',
  text: 'PlainTextGrammar',
  tml: 'TOML',
  toml: 'TOML',
  ts: 'TypeScript',
  txt: 'PlainTextGrammar',
  xml: 'XML',
  yaml: 'YAML',
  yml: 'YAML',
};
