
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-25T12:49:39+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "263d1b3ef20a0a6263fa82e7805ec09da460c524",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
