
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-25T18:35:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d6dd463a9f963a26af43cdc8ceff38ed6338f28",
 "version": "6.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
