# coding: utf-8

"""
    Mozart platform API

    API for interacting with the Mozart platform.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: support@bang-olufsen.dk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mozart_api
from mozart_api.models.speech_enhance_range import SpeechEnhanceRange  # noqa: E501
from mozart_api.rest import ApiException


class TestSpeechEnhanceRange(unittest.TestCase):
    """SpeechEnhanceRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SpeechEnhanceRange
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = mozart_api.models.speech_enhance_range.SpeechEnhanceRange()  # noqa: E501
        if include_optional:
            return SpeechEnhanceRange(
                default=mozart_api.models.speech_enhance.SpeechEnhance(
                    value=1.337,
                ),
                range=[
                    mozart_api.models.speech_enhance.SpeechEnhance(
                        value=1.337,
                    )
                ],
            )
        else:
            return SpeechEnhanceRange(
                default=mozart_api.models.speech_enhance.SpeechEnhance(
                    value=1.337,
                ),
                range=[
                    mozart_api.models.speech_enhance.SpeechEnhance(
                        value=1.337,
                    )
                ],
            )

    def testSpeechEnhanceRange(self):
        """Test SpeechEnhanceRange"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
