# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client/couchbase_version.py
# at
#    2023-08-25 13:39:56.419474
__version__ = '4.1.8'