from docassemble.base.config import AZURE_ENABLED as AZURE_ENABLED, S3_ENABLED as S3_ENABLED, azure_config as azure_config, s3_config as s3_config

def get_cloud(): ...
def get_custom_cloud(provider, config): ...
