from docassemble.base.logger import logmessage as logmessage
from docassemble.webapp.daredis import r as r, r_user as r_user
from docassemble.webapp.server import Role as Role, UserDict as UserDict, UserDictKeys as UserDictKeys, UserModel as UserModel, app as app, db as db, error_notification as error_notification, login_user as login_user, obtain_lock_patiently as obtain_lock_patiently, release_lock as release_lock, reset_user_dict as reset_user_dict, save_user_dict as save_user_dict, set_request_active as set_request_active, unpack_dictionary as unpack_dictionary, user_interviews as user_interviews
from docassemble.webapp.users.models import UserRoles as UserRoles

cron_type: str

def get_filenames(): ...
def get_records(filename, last_index): ...
def get_cron_user(): ...
def delete_inactive_users() -> None: ...
def clear_old_interviews() -> None: ...
def run_cron(the_cron_type) -> None: ...
