from _typeshed import Incomplete
from docassemble.base.config import daconfig as daconfig
from docassemble.base.error import DAException as DAException

credential_json: Incomplete
credential_info: Incomplete

def google_api_credentials(scope): ...
def google_cloud_credentials(): ...
def project_id(): ...
def google_cloud_storage_client(): ...
def google_cloud_vision_client(): ...
