# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client/./couchbase_version.py
# at
#    2023-08-25 13:38:15.955420
__version__ = '4.1.8'