# Generated by Django 3.2 on 2023-08-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion_counters', '0003_promotionprogram_repeatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementcounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='promotionprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='promotionprogram',
            name='repeatable',
            field=models.BooleanField(default=False, help_text='If enabled, the achievement counter will be recreated after the achievement is reached.', verbose_name='Repeatable'),
        ),
    ]
