# Generated by Django 4.2.2 on 2023-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_partner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="headquarter",
            name="partner_slug",
            field=models.SlugField(
                default="",
                help_text="Slug of headquarter",
                max_length=150,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
