
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-25T23:46:35+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fa1630b30379385beb46010ed7ee5e5eee911f0",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
