from docassemble.base.config import daconfig as daconfig, parse_redis_uri as parse_redis_uri
from docassemble.base.logger import logmessage as logmessage
from docassemble.webapp.cloud import get_cloud as get_cloud

def errlog(text) -> None: ...
def main() -> None: ...
