from _typeshed import Incomplete
from docassemble.base.config import daconfig as daconfig
from docassemble.base.logger import logmessage as logmessage
from docassemble.webapp.info import system_packages as system_packages

installed_distribution_cache: Incomplete
USING_SUPERVISOR: Incomplete
SINGLE_SERVER: Incomplete

def fix_fnctl() -> None: ...
def remove_inactive_hosts(start_time: Incomplete | None = ...) -> None: ...

class DummyPackage:
    name: Incomplete
    type: str
    limitation: Incomplete
    def __init__(self, name) -> None: ...

def clear_invalid_package_auth(start_time: Incomplete | None = ...) -> None: ...
def check_for_updates(start_time: Incomplete | None = ..., invalidate_cache: bool = ..., full: bool = ...): ...
def update_versions(start_time: Incomplete | None = ...) -> None: ...
def get_home_page_dict(): ...
def add_dependencies(user_id, start_time: Incomplete | None = ...): ...
def fix_names() -> None: ...
def splitall(path): ...
def install_package(package, start_time: Incomplete | None = ...): ...
def uninstall_package(package, start_time: Incomplete | None = ...): ...

class Object:
    def __init__(self, **kwargs) -> None: ...

def invalidate_installed_distributions_cache() -> None: ...
def get_installed_distributions(start_time: Incomplete | None = ...): ...
def get_pip_info(package_name, start_time: Incomplete | None = ...): ...
def main() -> None: ...
