# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lingvo/core/ops/record.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1clingvo/core/ops/record.proto\x12\x11tensorflow.lingvo\x1a&tensorflow/core/framework/tensor.proto\"\x87\x01\n\x06Record\x12\x35\n\x06\x66ields\x18\x01 \x03(\x0b\x32%.tensorflow.lingvo.Record.FieldsEntry\x1a\x46\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.tensorflow.TensorProto:\x02\x38\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lingvo.core.ops.record_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORD_FIELDSENTRY._options = None
  _RECORD_FIELDSENTRY._serialized_options = b'8\001'
  _RECORD._serialized_start=92
  _RECORD._serialized_end=227
  _RECORD_FIELDSENTRY._serialized_start=157
  _RECORD_FIELDSENTRY._serialized_end=227
# @@protoc_insertion_point(module_scope)
