__title__ = "bingx_headers_generator"
__description__ = "BingX Headers Generator that allows to access most of the BingX API endpoints"
__version__ = "1.0.3"
__author__ = "niewiemczego"
__license__ = "MIT"
