
def messie():
    art='''
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#&&&&&&&&&&###########&##&&&&&&&&&&&###########&&&&@@&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&##&&&&##GGBGGGG#&&&&&&&&&&&&&######&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&############BBBB###B5Y?5PY?7!~Y######&&&&&&######&&##############&&&&&&&&####&&&&&&&&&&&
&&&&&&######BBBBBBBBBBBBBBBBBBBJ5J!!!!^!!::G#BB####&&###############B##############&###############&
&&&&&&&##############BBBBBBBBB5JJ^~^^~~?5YJG###BBBB#####BBBB#BB############################&########
&&&&&&&&&######&#&&&&###BBB#B577:~!^~?JJYPB###BBBBBBB####BBBBBBBB##############B####################
&&&&&&&&&&&##&&#####&######BY7!:^!~^7JJY5PBBBBBBBBBBBB####BB###BBBBBBBB#######BB###B#BBBB####BB#####
&&&&&&&&&&&&&&##BBB#######BP7Y?^^^~Y?7JPBBBBBBGBBBBGBBBBBBBBBBBBBBBBBBB#####BBBBB####BBB####BBBB####
&#BBBB#&&&&########BBBBB#BBBG5J7!!Y5!JBGGGBBBBGBBBBBBBBBBGGGGBBBGGBBB#####BBBBBBB####B####BBGGGBBB##
&#BGGBB#&&&####B5PBBBGB&&&&&&#PJJYY?~JBGGGBBBBGGBBBBBBBBBGGGGGGGGGGGBGGGGGGGGGGGGGGGGGGBBBGGGGGGGGBB
BBGGGBBB#&####G~:.?BGG#&&&&#&&&#Y!^~~PBGGGGGGGGGGGBBBGGBBBGGPPPPPPPPPPPPPPPPPPGGGGGGGGGGGGGGGGGGGGGG
BBBBBBBB#####BG?!7YGGGB#&&&&&&&&P!~~~GBGGGGGGBGGBB##BBBBB#BBGGGGGGGGGGGGGGGGGGBBBBBBBBBBBBBBBBBBBBBB
B#####BBBBBBBBBBBGGGGBBBBBB####PY?!~JBBBBBBBBBBBBBGBBBBBBBBBBBBBBBBBBBGGBBBBBBBBBBBB##BBBBBBBBBBBBB#
BBB####BBBGGGBBGGGBBGGGGBGP5PGBYJ7!~5BBBBBBBBBBGBGG####BBBBBBBGGGGGGGBGGBBBBBBBBBBBBBBBBBBBBBBBBBBB#
BBBBBBBBBGGGGBGGGBBBBGGGGGGGGGG?Y?7~YBBBBBBBBBBBPYYYYJ?JYBBBBBBBBGBBBBBBBBBBBBBBBBBBBBBBBB#BBBBBBBBB
BBBBBBBBGGGGGGGGGBB#BGGPPPGGGGY?J7!~JBB##BBBBBG57!?JJ?7!^!BGGBBBBGBBBBGGBBBBBBGBBBBBBBBBBBBBBBBBGGBB
BBBBBGBBGGPPGGGGPGGBBGGGPPPGGP7JJ?!~?BB####BB5J7~J5PPJ7557YBGGBBBBGBBGGGGGGGGGGGBBGGBB##BGGPGBBGGGGB
BGGGGGGGGPPPGBBGPPPPPPGGGPPPGJ?5YJJ7?GBBBBBBP7?~~??J??!??!!5GGGBGGGGGGGGGPPPPPGGGGBGGGBBBBGGGGGGGGGG
BBGGGGGGPPPPGGGGGPPPPPPPPPPPP?Y55YJJYGGGGGGG5JJ?JJ5PP5YJJ!~YBGGGGGGGGGPPPPPPGGGBBGGPPPGGGBGGGGPPGGGG
BBGGP55PGPPPPGBBBGP55Y5PPPPP5J5PP5Y?Y55PPGGPP5??5PP555Y55J??Y5PPPPP55555555PPGGBGP55PPPPPGGGGGGGGGGG
GGPPP555PPGPPPPPP55555PPPPPP5J5PPYY7J5JY5P5YYY7?5GBP55J555YJ?JYYYYYYYYY55555555PPPPPP555555555P555YY
PPPPGG55PPP5P5YJ??J5PP5555555Y5P55J7^JY:!JJJ?J7?PBBBBBGPY5YJJ?YYJYYYYYYYYY55YYY55PPP55YYYYYYYYYJ??77
55YYPP55555555YJJJYY55Y55Y5Y555GBB5J!YY..:::^7JJY5GGBPJ!5BBGYY555555555PP5PPPPPPPPPPP55YYYYYY55YYJJJ
PPPPPPP55PPPPPPPPPPGGGGPPGGGGGP5B#GYYG~::::...~Y5J7?J?!?YPP5?7YGBBBGGGBBBBB###BGP5YY55555555555PPP55
B#####GPPG###&#&#######&&&&&&&&BYPGPB7^~^^^:..7J!??7??!GY777!!5BBBBBBBBBBBBBGPGG5YYYJJJJYY55YYJJJYYY
5PPGB#BGGB####&##BBBG55PB####BB#P7YP?!!~^~^~^^?Y?^:?YYJ7:.~~~~YBBBBBGGGGGP5?777JYJYY?7777JYJ?7!!!7??
7JJJ5BBGBBGPPPPPPPGP?!~!JPGGGPP5PY?J?!~~~~~~?J7YY?^^77?~..:!J?^~YBBBGGGBGPJ7!!7JJJ55JJ??JY5YYJ??JY5Y
7?JJYB##BBG5YJJ?Y5PY?7!!?5BG5Y??JY!!!?5?~~~~?PJJ5YY~~~~!^::^7?7::P##BGGBBG5YJJYPGGBBGGGGP5555GGGGGGG
Y5PPPB####BY?7!!7JJ?7JJ?J5#GY7!!7J!~!Y#?^!~~J5PJ7^^:^^^!~:::~!?^:?##BBGGGP5YJJY5YPYY5P5J7!~~!?YJJYYY
GB##BBBB###PJ????55JJ5GPPGBB5JJJYPJ!!7B?~~^~YPY5?:^^~7!7!:::~!!^^?#BBB5JJJJJJJJ77!7!??7!~^~^~!?77J??
BB#BGGBBGGBG5YYYY55YY5555555YYJJJYJ?77G7~^^!Y55Y?^^~^77?7::::~!^^YBGG5J????JYJ????????JJ?77?JY55YJJJ'''

    print(art)