from _typeshed import Incomplete
from docassemble.base.mako import exceptions as exceptions
from docassemble.base.mako.lookup import TemplateLookup as TemplateLookup
from docassemble.base.mako.template import Template as Template

def varsplit(var): ...
def _exit() -> None: ...
def cmdline(argv: Incomplete | None = ...) -> None: ...
