# coding: utf-8

"""
    Mozart platform API

    API for interacting with the Mozart platform.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: support@bang-olufsen.dk
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from datetime import datetime
from typing import List, Dict, Literal, Optional

from mozart_api.models.overlay_play_request_text_to_speech_text_to_speech import (
    OverlayPlayRequestTextToSpeechTextToSpeech,
)

from mozart_api.configuration import Configuration


class OverlayPlayRequestTextToSpeech(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"text_to_speech": "OverlayPlayRequestTextToSpeechTextToSpeech"}

    attribute_map = {"text_to_speech": "textToSpeech"}

    def __init__(
        self,
        text_to_speech: Optional[OverlayPlayRequestTextToSpeechTextToSpeech] = None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """OverlayPlayRequestTextToSpeech - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._text_to_speech = None
        self.discriminator = None

        if text_to_speech is not None:
            self.text_to_speech = text_to_speech

    @property
    def text_to_speech(self):
        # type: () -> OverlayPlayRequestTextToSpeechTextToSpeech
        """Gets the text_to_speech of this OverlayPlayRequestTextToSpeech.  # noqa: E501


        :return: The text_to_speech of this OverlayPlayRequestTextToSpeech.  # noqa: E501
        :rtype: OverlayPlayRequestTextToSpeechTextToSpeech
        """
        return self._text_to_speech

    @text_to_speech.setter
    def text_to_speech(self, text_to_speech):
        # type: (OverlayPlayRequestTextToSpeechTextToSpeech) -> None
        """Sets the text_to_speech of this OverlayPlayRequestTextToSpeech.


        :param text_to_speech: The text_to_speech of this OverlayPlayRequestTextToSpeech.  # noqa: E501
        :type text_to_speech: OverlayPlayRequestTextToSpeechTextToSpeech
        :rtype: None
        """

        self._text_to_speech = text_to_speech

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OverlayPlayRequestTextToSpeech):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OverlayPlayRequestTextToSpeech):
            return True

        return self.to_dict() != other.to_dict()
