
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-18T09:10:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b0f28d537bf5a7f59e4924f00d2f309a6362ae1",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
