# Generated by Django 3.2.5 on 2023-08-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('promotion_counters', '0002_promotionprogram_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionprogram',
            name='repeatable',
            field=models.BooleanField(default=False, verbose_name='Repeatable'),
        ),
    ]
