VERSION = '0.9.0'

ROUNDING = 10
MARGIN = ROUNDING + 10

STYLESHEET = None

DEFAULTFONTFAMILY = 'Open Sans'
DEFAULTFONTSIZE = '10px'
DEFAULTFONTSTYLE = None
DEFAULTFONTWEIGHT = None 
DEFAULTFONTDECORATION = None   