
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-28T18:30:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aba4d25dfa1941a52fc63c5bf752213edb563cc1",
 "version": "0.18.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
