# This file was auto-generated by Fern from our API Definition.

import typing

from .metric_response_object_resource import MetricResponseObjectResource
from .profile_response_object_resource import ProfileResponseObjectResource

GetEventResponseCollectionCompoundDocumentIncludedItem = typing.Union[
    MetricResponseObjectResource, ProfileResponseObjectResource
]
