# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client/couchbase_version.py
# at
#    2023-08-25 15:39:19.653019
__version__ = '4.1.8rc1'