# coding: utf-8

"""
    VRt.Agro [AG]

    The version of the OpenAPI document: 6.13.2112

    Generated by OpenAPI Generator: 6.6.0

    Do not edit the code manually

    2023 Veeroute
"""


from inspect import getfullargspec
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OperationType(str, Enum):
    """
    Type of [operation](#section/Description/Project):   * `HARVEST` - Harvesting crops   * `STORE` - Crop storage   * `DRY` - Drying crop   * `RELOCATE` - Transportation between production facilities   * `CONSUMPTION` - Plant crop consumption   * `LOAD` - Loading a crop into a storage location   * `UNLOAD` - Unload crop from storage location   * `SELL` - Sale of crop from the elevator to the market (under a specific contract)   * `BUY` - Buying a crop from the market to the factory (under a specific contract) 
    """

    """
    allowed enum values
    """
    HARVEST = 'HARVEST'
    STORE = 'STORE'
    DRY = 'DRY'
    RELOCATE = 'RELOCATE'
    CONSUMPTION = 'CONSUMPTION'
    LOAD = 'LOAD'
    UNLOAD = 'UNLOAD'
    SELL = 'SELL'
    BUY = 'BUY'

