# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>  # noqa: E501

    The version of the OpenAPI document: 0.63.0
    Contact: dev@swadesh.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class BypassableErrors(str, Enum):
    """
    BypassableErrors
    """

    """
    allowed enum values
    """
    ACCOUNT_OWNER_WATCHLIST = 'ACCOUNT_OWNER_WATCHLIST'
    DURATION_CONFLICT = 'DURATION_CONFLICT'
    EXTERNAL_ACCOUNT_NOT_ACTIVE = 'EXTERNAL_ACCOUNT_NOT_ACTIVE'
    EXTERNAL_ACCOUNT_NOT_VERIFIED = 'EXTERNAL_ACCOUNT_NOT_VERIFIED'
    EXTERNAL_ACH_DISABLED_FOR_TENANT = 'EXTERNAL_ACH_DISABLED_FOR_TENANT'
    FRAUD_DETECTED = 'FRAUD_DETECTED'
    IMPROPER_ACCOUNT_CUSTOMER_RELATIONSHIP = 'IMPROPER_ACCOUNT_CUSTOMER_RELATIONSHIP'
    IMPROPER_ACCOUNT_STATUS = 'IMPROPER_ACCOUNT_STATUS'
    IMPROPER_CUSTOMER_STATUS = 'IMPROPER_CUSTOMER_STATUS'
    IMPROPER_CUSTOMER_VERIFICATION_STATUS = 'IMPROPER_CUSTOMER_VERIFICATION_STATUS'
    IMPROPER_PARTNER_LIFECYCLE_STATUS = 'IMPROPER_PARTNER_LIFECYCLE_STATUS'
    IMPROPER_PARTNER_VERIFICATION_STATUS = 'IMPROPER_PARTNER_VERIFICATION_STATUS'
    PARTIAL_HOLDS_DISABLED = 'PARTIAL_HOLDS_DISABLED'

    @classmethod
    def from_json(cls, json_str: str) -> BypassableErrors:
        """Create an instance of BypassableErrors from a JSON string"""
        return BypassableErrors(json.loads(json_str))


