from _typeshed import Incomplete
from docassemble.base.mako import exceptions as exceptions
from docassemble.base.mako.cache import CacheImpl as CacheImpl

has_beaker: bool
_beaker_cache: Incomplete

class BeakerCacheImpl(CacheImpl):
    def __init__(self, cache) -> None: ...
    def _get_cache(self, **kw): ...
    def get_or_create(self, key, creation_function, **kw): ...
    def put(self, key, value, **kw) -> None: ...
    def get(self, key, **kw): ...
    def invalidate(self, key, **kw) -> None: ...
