from _typeshed import Incomplete
from docassemble.base.logger import logmessage as logmessage

class GeoCoder:
    server: Incomplete
    def __init__(self, *pargs, **kwargs) -> None: ...
    data: Incomplete
    def geocode(self, *pargs, **kwargs): ...

class GoogleV3GeoCoder(GeoCoder):
    def config_ok(self): ...
    geocoder: Incomplete
    def initialize(self) -> None: ...
    def populate_address(self, address) -> None: ...

class AzureMapsGeoCoder(GeoCoder):
    def config_ok(self): ...
    geocoder: Incomplete
    def initialize(self) -> None: ...
    def populate_address(self, address) -> None: ...
