# Generated by Django 4.2.2 on 2023-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_partner", "0004_alter_partner_partner_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="partner_slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Slug of headquarter",
                max_length=150,
                null=True,
                verbose_name="slug",
            ),
        ),
    ]
