from .ZaidPy import A_Gmail
from .ZaidPy import A_Yahoo
from .ZaidPy import A_Aol
from .ZaidPy import A_Hotmail
from .ZaidPy import A_MailRu
from .ZaidPy import CheckTik
from .ZaidPy import CheckInsta
from .ZaidPy import GetInfoTik
from .ZaidPy import GetInfoInsta
from .ZaidPy import GetListTik_FG
from .ZaidPy import GetListTik_RM